language: python

cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO_VERSION=">=1.11.15,<2.0"
  - DJANGO_VERSION=">=2.0"

install:
  - pip install -r requirements-dev.txt
  - pip install -q Django$DJANGO_VERSION

script:
  - flake8 djlotrek
  - make test
  - codecov
